-- PRO-LEVEL DATABASE HARDENING
-- Run this in your Supabase SQL Editor.

-- 1. Reset Table
DROP TABLE IF EXISTS predictions CASCADE;

CREATE TABLE predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  expected_odds TEXT,
  bet_code TEXT NOT NULL, -- Sensitive column
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;

-- 3. Column-Level Security (THE PRO WAY)
-- By default, revoke all public access to the table
REVOKE ALL ON predictions FROM anon;
REVOKE ALL ON predictions FROM authenticated;

-- Grant limited access to the Public (anon)
-- They can ONLY see non-sensitive columns
GRANT SELECT (id, title, price, expected_odds, created_at) ON predictions TO anon;

-- Grant full access to Authenticated (Admin)
GRANT ALL ON predictions TO authenticated;
-- Important: Grant access to service_role (used by server)
GRANT ALL ON predictions TO service_role;

-- 4. RLS Policies (Row Filter)
-- Allow public to see rows (but they can only see columns granted above)
CREATE POLICY "Public Read Access" ON predictions FOR SELECT TO anon USING (true);

-- Allow authenticated users (Admin) to do everything
CREATE POLICY "Admin Full Access" ON predictions FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 5. Helper Function for Admin (Optional but good)
-- If you need to check if a code exists without revealing it
-- 6. Transaction Tracking (Anti-Replay Attack)
CREATE TABLE successful_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference TEXT UNIQUE NOT NULL,
  prediction_id BIGINT REFERENCES predictions(id),
  amount NUMERIC,
  customer_email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE successful_payments ENABLE ROW LEVEL SECURITY;
GRANT ALL ON successful_payments TO authenticated;
GRANT ALL ON successful_payments TO service_role;
-- No public access to see who paid what
REVOKE ALL ON successful_payments FROM anon;
