-- PRO-LEVEL DATABASE HARDENING
-- Run this in your Supabase SQL Editor.

-- ==========================================
-- 1. PREDICTIONS TABLE (Main Data)
-- ==========================================
DROP TABLE IF EXISTS predictions CASCADE;

CREATE TABLE predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  expected_odds TEXT,
  bet_code TEXT NOT NULL, -- Sensitive column
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices for performance
CREATE INDEX idx_predictions_created_at ON predictions(created_at DESC);

-- Enable RLS
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;

-- Column-Level Security (Anon can NOT see bet_code)
REVOKE ALL ON predictions FROM anon;
REVOKE ALL ON predictions FROM authenticated;

-- Public can ONLY see non-sensitive columns
GRANT SELECT (id, title, price, expected_odds, created_at) ON predictions TO anon;

-- Admin/Service Role can see everything
GRANT ALL ON predictions TO authenticated;
GRANT ALL ON predictions TO service_role;

-- RLS Policies
CREATE POLICY "Public Read Access" 
  ON predictions FOR SELECT 
  TO anon 
  USING (true);

CREATE POLICY "Admin All Access" 
  ON predictions FOR ALL 
  TO authenticated 
  USING (true) 
  WITH CHECK (true);

-- ==========================================
-- 2. SUCCESSFUL PAYMENTS (Tracking & Anti-Replay)
-- ==========================================
DROP TABLE IF EXISTS successful_payments CASCADE;

CREATE TABLE successful_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference TEXT UNIQUE NOT NULL,
  prediction_id BIGINT REFERENCES predictions(id) ON DELETE SET NULL,
  amount NUMERIC,
  customer_email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices for performance and tracking
CREATE INDEX idx_payments_reference ON successful_payments(reference);
CREATE INDEX idx_payments_prediction_id ON successful_payments(prediction_id);

-- Enable RLS
ALTER TABLE successful_payments ENABLE ROW LEVEL SECURITY;

-- Access Control
REVOKE ALL ON successful_payments FROM anon;
GRANT ALL ON successful_payments TO authenticated;
GRANT ALL ON successful_payments TO service_role;

-- Policies
CREATE POLICY "Admin Manage Payments" 
  ON successful_payments FOR ALL 
  TO authenticated 
  USING (true) 
  WITH CHECK (true);

-- Comment for documentation
COMMENT ON COLUMN predictions.bet_code IS 'SENSITIVE: Only accessible via server-side verification or service_role.';
COMMENT ON TABLE successful_payments IS 'Stores verified Paystack transactions to prevent double-claiming of bet codes.';
